import org.junit.Test;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'robson' at '28/10/15 21:51' with Gradle 2.6
 *
 * @author robson, @date 28/10/15 21:51
 */
public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
    	/*fail();*/
        Library classUnderTest = new Library();
        /*assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());*/
    }
}
