/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'robson' at '28/10/15 21:51' with Gradle 2.6
 *
 * @author robson, @date 28/10/15 21:51
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
